const ACTION_TYPE = {
  GET_JOBS: "GET_JOBS",
  GET_JOB_TYPES: "GET_JOB_TYPES",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_JOBS_BY_TYPE: "GET_JOBS_BY_TYPE",
  LOG_IN: "LOG_IN",
  SIGN_UP: "SIGN_UP"
};
export default ACTION_TYPE;
