const ACTION_TYPE = {
  GET_JOBS: "GET_JOBS",
  GET_JOB_TYPES: "GET_JOB_TYPES",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_JOBS_BY_TYPE: "GET_JOBS_BY_TYPE",
  LOG_IN: "LOG_IN",
  SIGN_UP: "SIGN_UP",
  GET_PROFILE: "GET_PROFILE",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  LOG_OUT: "LOG_OUT",
};
export default ACTION_TYPE;
